import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './[Comps]/SideBar'
import FollowBar from './[Comps]/FollowBar'
import { Toaster } from '@/components/ui/toaster'
import SessionProvider from '@/utils/NextAuthProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className='grid grid-cols-4 mt-5'>
            <SideBar />
            <div className='col-span-2'>
              {children}
            </div>
            <FollowBar />
            <Toaster />
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
